version: 2
updates:
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    # Look for workflow files in the `.github/workflows` directory
    directory: ".github/workflows"
    # Check for updates once a week
    schedule:
      interval: "weekly"
